src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProjectRepository::class)
 */
class Project
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $started_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $ended_at;

     /**
     * @ORM\Column(type="string")
     */
    private $status;

     /**
     * @ORM\OneToMany(targetEntity=Task::class, mappedBy="project")
     */
    private $tasks;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStartedAt(): ?\DateTimeInterface
    {
        return $this->started_at;
    }

    public function setStartedAt(\DateTimeInterface $started_at): self
    {
        $this->started_at = $started_at;

        return $this;
    }

    public function getEndedAt(): ?\DateTimeInterface
    {
        return $this->ended_at;
    }

    public function setEndedAt(\DateTimeInterface $ended_at): self
    {
        $this->ended_at = $ended_at;

        return $this;
    }



    /**
     * Get the value of status
     */ 
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set the value of status
     *
     * @return  self
     */ 
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get the value of tasks
     */ 
    public function getTasks()
    {
        return $this->tasks;
    }

    /**
     * Set the value of tasks
     *
     * @return  self
     */ 
    public function setTasks($tasks)
    {
        $this->tasks = $tasks;

        return $this;
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Entity\Project;
use App\Entity\Task;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ProjectRepository;
use App\Repository\TaskRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class ProjectController extends AbstractController
{
    /**
     * @Route("/project", name="project")
     */
    public function index(): Response
    {
        return $this->render('project/index.html.twig', [
            'controller_name' => 'ProjectController',
        ]);
    }

     /**
     *@Route("/", name="project_list")
     */
    public function liste(ProjectRepository $projectRepository): Response
    {
        $projects =  $projectRepository->findAll();
        return $this->render('project/list.html.twig', ['projects' => $projects]);

    }

    /**
     * @Route("/add", name="project_add")
     */
    public function add(Request $request, EntityManagerInterface $entityManager, TaskRepository $taskRepository)
    {
   
        if ($request->getMethod() === 'POST') {
            $project = new Project();
            $project->setName($request->request->get('name'));
            $project->setStartedAt(new \DateTime);
            $project->setEndedAt(new \DateTime);
            $project->setStatus("nouveau");



            $entityManager->persist($project);
            $entityManager->flush();

            return $this->redirectToRoute('project_list');
        }

        return $this->render('project/add.html.twig');
    }
  
    public function update(int $id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $project = $entityManager->getRepository(Project::class)->find($id);

        if (!$project) {
            throw $this->createNotFoundException(
                'No product found for id '.$id
            );
        }

        $project->setStatus();
        $entityManager->flush();

        return $this->redirectToRoute('project_list', [
            'id' => $project->getId()
        ]);
    }
    /**
     *@Route("/project/{id}", name="project_gestion")
     *@param $id
     *@param ProjectRepository $projectRepository
     */
    public function show($id, ProjectRepository $projectRepository)
    {
     $project = $projectRepository->find($id);
     if ($project== null) {
         throw new NotFoundHttpException();
     }
     return $this->render('project/gestion.html.twig', ['project' => $project]);
    }
    
}

templates/project/add.html.twig
{% extends "base.html.twig" %}
 {% block stylesheets %}
        <link rel="stylesheet"  href="{{ asset('style/style.css')}} " />
  {% endblock %}
{% block title %}Créer un projet{% endblock %}

{% block body %}
<h1>Ajouter un projet</h1>
    <form action="" method="post">
     <h2>Nom du projet</h2> <br> 
     <textarea id="story" name="name" rows="5" cols="33">
</textarea><br>
    <button type="submit">Ajouter</button>
    </form>
{% endblock %}

templates/project/gestion.html.twig
{% extends "base.html.twig" %}
 {% block stylesheets %}
        <link rel="stylesheet"  href="{{ asset('style/style.css')}} " />
  {% endblock %}

{% block body %}

<h1>Projet : {{ project.name }}</h1>
<h2>Créer le : {{ project.startedAt|date('Y-m-d') }} </h2>
        <form action="" method="post">
        <select name="status" id="day">
            {% if project.status == "Nouveau" %}
                <option value="Nouveau">{{ project.status }}</option>
                <option value="En cours">En cours</option>
                <option value="Terminé">Terminé</option>
            {% elseif project.status == "En cours" %}
                <option value="En cours">{{ project.status }}</option>
                <option value="Nouveau">Nouveau</option>
                <option value="Terminé">Terminé</option>
            {% else %}
                <option value="Terminé">Terminé</option>
                <option value="Nouveau">Nouveau</option>
                <option value="En cours">En cours</option>
            {% endif %}
        </select>
        <button type="submit">Changer</button>
        </form>
   <a href="{{ path('add_task', {id: project.id})}}">Ajouter une tache</a> 
{% for task in project.tasks %}
    <h3> Nom de la tâche :  {{ task.title}}</h3>
    <h3> Description de la tâche : {{ task.description}}</h3>
    <h3> date de création de la tâche : {{ task.createdAt|date('Y-m-d')}}</h3>
{% endfor %}

{% endblock %}

templates/project/list.html.twig
{% extends "base.html.twig" %}
 {% block stylesheets %}
        <link rel="stylesheet"  href="{{ asset('style/style.css')}} " />
  {% endblock %}
{% block body %}
<h1>Projects</h1>
<a href=" {{ path('project_add') }}">Ajouter un projet</a>
 {% for project in projects %}
     <h2> Nom du project :  {{ project.name }} </h2>
     <h2>Statut : {{ project.status }}</h2>
   <h2> Ajouté le : {{ project.startedAt|date('Y-m-d') }} </h2>
     <small>Nombre de Tâches : {{ project.tasks|length }}</small>
<a href=" {{ path('project_gestion', {id: project.id}) }}">Gérer</a>
   
 {% endfor %}

    


{% endblock %}